## [Problem 1]: Enumeration of classes used so far

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


### Pandas:
<li> DataFrame
<li> Series

### matplotlib

<li> pyplot

### scikit-learn

<li> LinearRegression
<li> StandardScaler
<li> DecisionTree
<li> RandomForest
<li> SVR

## [Problem 2]: Enumeration of methods and instance variables used so far


When it comes to dotting, you have probably used ndarray.shape and ndarray.sum() for NumPy's ndarray many times. This means that ndarray is also an instance object,shapeis an instance variable, and sumis a method.


Any data that appears in Python code is an instance object, and list and str also have methods.

### Some instance variable:
<li> numpy shape
<li> iris_data.filename
<li> iris_data.target
<li> iris_data.feature_names
<li> iris_data.target_names
    
### Some method:
<li> pandas concat
<li> pandas query with loc and iloc
<li> seaborn pairplot
<li> seaborn scatter plot
<li> seaborn box plot
<li> seaborn violin plot
<li> train_test_split
<li> sklearn fit
<li> sklearn transform
<li> sklearn predict
    

## [Problem 3]: Creating a standardized class by scratch

In [1]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X,axis=0)
        self.var_ = np.var(X,axis=0)
        pass
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - np.mean(X,axis=0))/np.sqrt(np.var(X,axis=0))
        return X_scaled

In [3]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


## [Problem 4]: Creating a class that performs 4 arithmetic operations


In [7]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        """
        Raise exception
        """
        if(type(value)!= int) and (type(value)!=float):
            raise TypeError("Only integer and float are allowed")
            
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    def subtract(self,value2):
        self.value -= value2
    def mul(self,value2):
        self.value *= value2
    def div(self,value2):
        self.value /= value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.subtract(3)
print("value : {}".format(example.value))
example.mul(3)
print("value : {}".format(example.value))
example.div(3)
print("value : {}".format(example.value))
example = ExampleClass("asas")

初期値5が設定されました
value : 5
value : 8
value : 5
value : 15
value : 5.0


TypeError: Only integer and float are allowed