# Matrix product

## [Problem 1]: Matrix product is calculated manually

For a position (n,m) of matrix C, it would be calculated using dot product from row n from the matrix A and column m of matrix B.

To solve the above problem, we calculate each elements:
<br>
C[0,0] = A[0,0]xB[0,0] + A[0,1]xB[1,0] + A[0,2]xB[2,0] = 6
<br>
C[0,1] = A[0,0]xB[0,1] + A[0,1]xB[1,1] + A[0,2]xB[2,1] = 29
<br>
C[0,2] = A[0,0]xB[0,2] + A[0,1]xB[1,2] + A[0,2]xB[2,2] = -20
<br>
C[1,0] = A[1,0]xB[0,0] + A[1,1]xB[1,0] + A[1,2]xB[2,0] = 12

The rest is similar

The result :
$[[  6,  29, -20], \\
       [ 12,  52,  38], \\
       [-18, -51, -48]]$


## [Problem 2] Calculation by NumPy function

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
a_ndarray@b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## [Problem 3]: Implementation of calculation of a certain element


In [6]:
value = 0
for i in range(a_ndarray.shape[1]):
    value += a_ndarray[0,i]*b_ndarray[i,0]
value

6

## [Problem 4]: Creating a function that performs matrix multiplication

In [8]:
def matrix_multiply(matrix_a,matrix_b):
    value = np.zeros_like(matrix_a)
    for i in range(matrix_a.shape[1]):
        for j in range(matrix_a.shape[0]):
            value[i,j] = np.sum(matrix_a[i,:]*matrix_b[:,j])
    return value

result = matrix_multiply(a_ndarray,b_ndarray)
result

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## [Problem 5] Judge the input whose calculation is not defined

In [9]:
def matrix_multiply(matrix_a,matrix_b):
    if matrix_a.shape[1] != matrix_b.shape[0]:
        print("The number of columns of first matrix  is not equal to the number of rows of second matrix ")
    value = np.zeros_like(matrix_a)
    for i in range(matrix_a.shape[1]):
        for j in range(matrix_a.shape[0]):
            value[i,j] = np.sum(matrix_a[i,:]*matrix_b[:,j])
    return value
result = matrix_multiply(a_ndarray,b_ndarray)
result

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

##[ Problem 6: Transposition